[build-system]
requires = ["setuptools>=42", "wheel"]
build-backend = "setuptools.build_meta"
[project]
name = "data_assimilation_engine"
dynamic = ["version"]
description = "Tools for creating both spatial and timeseries visualizations of simulated and observed variables (SWE and soil moisture)."
readme = "README.md"
maintainers = [
    { name = "Kyle Larkin", email = "Kyle.S.Larkin@rtx.com" },
    {name = "Matthew Deshotel", email = "mdeshotel@dewberry.com"},
    {name = "Miguel Pena", email = "miguel.pena@rtx.com"}
]
classifiers = [
    "Development Status :: 4 - Beta",
    "Intended Audience :: Developers",
    "License :: OSI Approved :: BSD License",
    "Programming Language :: Python :: 3.11",
]
requires-python = "~=3.11"
dependencies = [
    "xarray[complete]==2025.12.0",
    "matplotlib~=3.10.6",
    "cartopy==0.25.0",
    # Use the same versions as mswm
    "numpy~=1.26.4",                        # Match ngen-forcing
    "scipy==1.16.1",
    "geopandas~=1.1.1",                     # Match ngen-forcing
    "shapely~=2.1.2",                       # Match ngen-forcing
    "pandas~=2.3.3",                        # Match ngen-forcing
    # fsspec and s3fs need to be locked together
    "fsspec==2025.3.0",
    "s3fs==2025.3.0",
    "dask[complete]==2025.7.0",  # Includes Dask core + recommended dependencies
    "distributed==2025.7.0",  # Adds support for parallel computing
    "requests~=2.32.5",
    "ruff==0.12.10",
    "python-dotenv~=1.2.1",
    "rioxarray==0.19.0",
    "boto3==1.40.17",
    "earthaccess==0.15.1",
    "ujson==5.11.0",
    "kerchunk==0.2.9",
    "h5py==3.15.1"
    ]
[project.urls]
repository = "https://github.com/NGWPC/data-assimilation-engine"
[tool.setuptools.packages.find]
where = ["."]
include = ["data_assimilation_engine*"]
[tool.setuptools.dynamic]
version = {attr = "data_assimilation_engine.__version__"}
[tool.ruff]
line-length = 88